language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - hhvm
  
before_script:
  - composer self-update
  - php composer.phar install --dev --no-interaction
  
script:
  - mkdir -p build/logs
  - phpunit -c phpunit.xml.dist

after_script:
  - php vendor/bin/coveralls

matrix:
  allow_failures:
    - php: hhvm
